qbox/urls.py
from django.conf.urls import include, url
from django.contrib import admin
urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('reg_sub.urls'))
]

reg_sub/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from reg_sub.views import *
urlpatterns = [
    url(r'^$', home),
]

reg_sub/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.hashers import is_password_usable
from django.utils.encoding import python_2_unicode_compatible
from django.utils import timezone
from django.conf import settings
from django.utils.translation import ugettext_lazy as _
import datetime


@python_2_unicode_compatible    #for python 2 compatibility
class Subscribe(models.Model):
    name = models.CharField(max_length=40, blank=False, default="")
    email = models.EmailField(blank=False)
    subject = models.CharField(max_length=100, blank=True)
    def __str__(self):
        return u'%s' % (self.email)


@python_2_unicode_compatible    #for python 2 compatibility
class Intern(models.Model):
    name = models.CharField(max_length=40, blank=False)
    email = models.EmailField(blank=False)
    contactno = models.CharField(max_length=15, blank=True, default="")
    interests = models.TextField(max_length=100, blank=False)
    def __str__(self):
        return u'%s' % (self.email)

reg_sub/forms.py
from django import forms
from reg_sub.models import Intern, Subscribe
import re




class internform(forms.Form):
    email = forms.EmailField(required=True)
    name = forms.CharField(max_length=40, required=True)
    contactno = forms.CharField(max_length=15, required=False)
    interests = forms.CharField(max_length=100, required=True, widget=forms.Textarea)
    def clean_email(self):
        email2 = self.cleaned_data['email']
        try:
            flag = Intern.objects.get(email=email2)
        except Intern.DoesNotExist:
            flag = None
        if flag is not None:
            raise forms.ValidationError("Email exists")
        return email2

    def __init__(self, *args, **kwargs):
        super(internform, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class' : 'form-control', 'placeholder': 'Name'})
        self.fields['email'].widget.attrs.update({'class' : 'form-control', 'placeholder': 'E-mail address'})
        self.fields['contactno'].widget.attrs.update({'class' : 'form-control', 'placeholder': '+99-9999999999'})
        self.fields['interests'].widget.attrs.update({'class' : 'form-control', 'placeholder': 'Your Interests'})

class subform(forms.Form):
    error_css_class = 'help-block with-errors'
    email = forms.EmailField(required=True)
    name = forms.CharField(max_length=40, required=True)
    subject = forms.CharField(max_length=100, required=True)
    def clean_email(self):
        email2 = self.cleaned_data['email']
        try:
            flag = Subscribe.objects.get(email=email2)
        except Subscribe.DoesNotExist:
            flag = None
        if flag is not None:
            raise forms.ValidationError("Email exists")
        return email2

    def __init__(self, *args, **kwargs):
        super(subform, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class' : 'form-control', 'placeholder': 'Your Name'})
        self.fields['email'].widget.attrs.update({'class' : 'form-control', 'placeholder': 'Your Email'})
        self.fields['subject'].widget.attrs.update({'class' : 'form-control', 'placeholder': 'Subject'})

reg_sub/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login as authlogin, logout as authlogout
from django.http import HttpResponse, Http404, HttpResponseRedirect, JsonResponse
from reg_sub.forms import subform, internform
from reg_sub.models import Intern, Subscribe
import json

# Create your views here.


def home(request):
    if request.method == 'POST':
        flag = request.POST['id']
        if flag == 'sub':
            form = subform(request.POST)
            if form.is_valid():
                cd = form.cleaned_data
                us = Subscribe(email=cd['email'], name=cd['name'], subject=cd['subject'])
                us.save()
            form1 = subform()
            form2 = internform()
            return render(request, 'reg_sub/index.html', {'alert': 1, 'form': form1, 'form2': form2})
        elif flag == 'intern':
            form = internform(request.POST)
            if form.is_valid():
                cd = form.cleaned_data
                us = Intern(email=cd['email'], name=cd['name'], contactno=cd['contactno'], interests=cd['interests'])
                us.save()
            form1 = subform()
            form2 = internform()
            return render(request, 'reg_sub/index.html', {'alert': 2, 'form': form1, 'form2': form2})
        else:
            form1 = subform()
            form2 = internform()
            return render(request, 'reg_sub/index.html', {'alert': 0, 'form': form1, 'form2': form2})
    else:
        form1 = subform()
        form2 = internform()
        return render(request, 'reg_sub/index.html', {'alert':0, 'form': form1, 'form2': form2})

'''
def signup(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('/reg/')
    else:
        if request.method == 'POST':
            form = signupform(request.POST, request.FILES)
            if form.is_valid():
                cd = form.cleaned_data
                username2 = cd['username']
                name2 = cd['name']
                email2 = cd['email']
                password2 = cd['password2']
                profile2 = cd['profile']
                contact2 = cd['contactno']
                college2 = cd['college']
                us = Qboxuser(name = name2, contactno = contact2 , username = username2, email=email2, profile = profile2, college = college2)
                us.set_password(password2)
                us.save()
                return HttpResponseRedirect('/reg/')
            else:
                return render(request, 'reg_sub/signup.html', {'form': form})
        else:
            form = signupform()
            return render(request, 'reg_sub/signup.html', {'form': form})

def subscribe(request):
    if request.method == 'POST':
        form = subform(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            us = Subscribe(email=cd['email'])
            us.save()
            return HttpResponseRedirect('/reg/')
        else:
            return render(request, 'reg_sub/subscribe.html', {'form': form})
    else:
        form = subform()
        return render(request, 'reg_sub/subscribe.html', {'form': form})
'''

reg_sub/templates/reg_sub/main.html
<html>
<head>
    <title>Main</title>
</head>

<body>
    <h1>Main</h1>

</body>
</html>

reg_sub/templates/reg_sub/signup.html
<html>
<head>
    <title>SignUp</title>
</head>

<body>
    <h1>SignUp</h1>

    {% if form.errors %}
        <p style="color: red;">
            Please correct the error(s) below.
        </p>
    {% endif %}

    <form action="" method="post" enctype="multipart/form-data">
        <div style="color: red">
            {{ form.name.errors }}
        </div>
            <label for="id_name">Name*:</label>

            {{ form.name }}


     <div style="color: red">
            {{ form.college.errors }}
        </div>
            <label for="id_country">Institution*:</label>

            {{ form.college }}

        <div style="color: red">
            {{ form.email.errors }}
        </div>
            <label for="id_email">Email*:</label>

            {{ form.email }}
  
     <div style="color: red">
            {{ form.contactno.errors }}
        </div>
            <label for="id_contact">Contact Number*:</label>

            {{ form.contactno }}


       <div style="color: red">
            {{ form.profile.errors }}
        </div>
            <label for="id_profile">Profile:</label>

            {{ form.profile }}

       <div style="color: red">
            {{ form.username.errors }}
        </div>
            <label for="id_username">Username*:</label>

            {{ form.username }}

       <div style="color: red">
            {{ form.password1.errors }}
        </div>
            <label for="id_password1">Password*:</label>

            {{ form.password1 }}

       <div style="color: red">
            {{ form.password2.errors }}
        </div>
            <label for="id_password">Confirm Password*:</label>

            {{ form.password2 }}




        {% csrf_token %}
        <input type="submit" value="Submit">
    </form>
</body>
</html>

reg_sub/templates/reg_sub/subscribe.html
<html>
<head>
    <title>Subscribe</title>
</head>

<body>
    <h1>Subscribe</h1>

    {% if form.errors %}
        <p style="color: red;">
            Please correct the error(s) below.
        </p>
    {% endif %}

    <form action="" method="post">
        <div style="color: red">
            {{ form.email.errors }}
        </div>
            <label for="id_email">Email*:</label>

            {{ form.email }}
 
        {% csrf_token %}
        <input type="submit" value="Submit">
    </form>
</body>
</html>

templates/css/fonts/ElegantIcons-2.html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /pro/dream/css/fonts/ElegantIcons.woff was not found on this server.</p>
<p>Additionally, a 404 Not Found
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>

templates/css/fonts/ElegantIcons-3.html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /pro/dream/css/fonts/ElegantIcons.ttf was not found on this server.</p>
<p>Additionally, a 404 Not Found
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>

templates/css/fonts/ElegantIcons-4.html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /pro/dream/css/fonts/ElegantIcons.svg was not found on this server.</p>
<p>Additionally, a 404 Not Found
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>

templates/css/fonts/ElegantIcons.html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /pro/dream/css/fonts/ElegantIcons.eot was not found on this server.</p>
<p>Additionally, a 404 Not Found
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>

templates/css/fonts/ElegantIconsd41d.html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /pro/dream/css/fonts/ElegantIcons.eot was not found on this server.</p>
<p>Additionally, a 404 Not Found
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>

templates/fonts/et-lined41dd41d.html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /pro/dream/fonts/et-lined41d.eot was not found on this server.</p>
<p>Additionally, a 404 Not Found
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>

templates/js/jquery.waypoints.min.html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /pro/dream/js/jquery.waypoints.min.js was not found on this server.</p>
<p>Additionally, a 404 Not Found
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>